<?php

namespace Database\Seeders;

use App\Models\Fauna;
use Illuminate\Database\Seeder;

class FaunaSeeder extends Seeder
{
    public function run(): void
    {
        $faunaData = [
            [
                'name' => 'Anoa Dataran Rendah',
                'local_name' => 'Anoa',
                'scientific_name' => 'Bubalus depressicornis',
                'description' => 'Kerbau terkecil di dunia yang hanya ditemukan di Sulawesi. Hewan ikonik TNLL dan sangat dilindungi.',
                'image_path' => 'fauna/fa1.jpg',
                'habitat' => 'Hutan hujan dataran rendah',
                'conservation_status' => 'EN',
                'category' => 'endemik',
                'is_featured' => true,
            ],
            [
                'name' => 'Tarsius Sulawesi',
                'local_name' => 'Tangkasi',
                'scientific_name' => 'Tarsius tarsier',
                'description' => 'Primata terkecil di dunia dengan mata besar dan aktif di malam hari. Endemik Sulawesi.',
                'image_path' => 'fauna/fa2.jpg',
                'habitat' => 'Hutan sekunder dan primer',
                'conservation_status' => 'VU',
                'category' => 'endemik',
                'is_featured' => true,
            ],
            [
                'name' => 'Maleo',
                'local_name' => 'Burung Maleo',
                'scientific_name' => 'Macrocephalon maleo',
                'description' => 'Burung endemik yang menetaskan telur menggunakan panas bumi. Hanya ada di Sulawesi.',
                'image_path' => 'fauna/fa3.jpg',
                'habitat' => 'Hutan pantai dan dataran rendah',
                'conservation_status' => 'EN',
                'category' => 'endemik',
                'is_featured' => true,
            ],
            [
                'name' => 'Babi Rusa',
                'local_name' => 'Babirusa',
                'scientific_name' => 'Babyrousa celebensis',
                'description' => 'Babi unik dengan taring melengkung ke atas menembus moncong. Endemik Sulawesi.',
                'image_path' => 'fauna/fa4.jpg',
                'habitat' => 'Hutan hujan tropis',
                'conservation_status' => 'VU',
                'category' => 'endemik',
                'is_featured' => true,
            ],
            [
                'name' => 'Monyet Tonkean',
                'local_name' => 'Monyet Hitam',
                'scientific_name' => 'Macaca tonkeana',
                'description' => 'Monyet endemik Sulawesi Tengah. Hidup berkelompok dan mudah dijumpai di TNLL.',
                'image_path' => 'fauna/fa5.jpg',
                'habitat' => 'Hutan primer dan sekunder',
                'conservation_status' => 'VU',
                'category' => 'endemik',
                'is_featured' => false,
            ],
            [
                'name' => 'Kuskus Beruang',
                'local_name' => 'Kuse',
                'scientific_name' => 'Ailurops ursinus',
                'description' => 'Marsupial arboreal terbesar di Sulawesi. Aktif di malam hari dan pemakan daun.',
                'image_path' => 'fauna/fa6.jpg',
                'habitat' => 'Kanopi hutan hujan',
                'conservation_status' => 'VU',
                'category' => 'endemik',
                'is_featured' => false,
            ],
            [
                'name' => 'Elang Sulawesi',
                'local_name' => 'Elang Bondol',
                'scientific_name' => 'Nisaetus lanceolatus',
                'description' => 'Elang endemik predator puncak di ekosistem TNLL. Berburu mamalia kecil dan reptil.',
                'image_path' => 'fauna/fa7.jpg',
                'habitat' => 'Hutan pegunungan',
                'conservation_status' => 'NT',
                'category' => 'endemik',
                'is_featured' => false,
            ],
            [
                'name' => 'Rangkok Sulawesi',
                'local_name' => 'Julang',
                'scientific_name' => 'Rhyticeros cassidix',
                'description' => 'Burung besar dengan tanduk di atas paruh. Penting untuk penyebaran biji hutan.',
                'image_path' => 'fauna/fa8.jpg',
                'habitat' => 'Hutan primer dataran rendah',
                'conservation_status' => 'VU',
                'category' => 'endemik',
                'is_featured' => false,
            ],
            [
                'name' => 'Kadal Terbang',
                'local_name' => 'Cikibor',
                'scientific_name' => 'Draco volans',
                'description' => 'Kadal dengan membran kulit untuk meluncur antar pohon. Pemandangan menarik di hutan.',
                'image_path' => 'fauna/fa9.jpg',
                'habitat' => 'Hutan tropis',
                'conservation_status' => 'LC',
                'category' => 'umum',
                'is_featured' => false,
            ],
            [
                'name' => 'Ular Sanca',
                'local_name' => 'Piton',
                'scientific_name' => 'Python reticulatus',
                'description' => 'Ular terpanjang di dunia. Predator puncak yang penting untuk keseimbangan ekosistem.',
                'image_path' => 'fauna/fa10.jpg',
                'habitat' => 'Hutan dan tepi sungai',
                'conservation_status' => 'LC',
                'category' => 'umum',
                'is_featured' => false,
            ],
            [
                'name' => 'Kupu-kupu Sayap Burung',
                'local_name' => 'Kupu Raksasa',
                'scientific_name' => 'Ornithoptera croesus',
                'description' => 'Kupu-kupu terbesar dan tercantik di Indonesia. Dilindungi dan bernilai tinggi.',
                'image_path' => 'fauna/fa11.jpg',
                'habitat' => 'Hutan hujan',
                'conservation_status' => 'NT',
                'category' => 'langka',
                'is_featured' => true,
            ],
            [
                'name' => 'Burung Nuri',
                'local_name' => 'Kasturi',
                'scientific_name' => 'Lorius garrulus',
                'description' => 'Burung berwarna-warni yang cerdas. Sering terdengar suaranya di hutan.',
                'image_path' => 'fauna/fa12.jpg',
                'habitat' => 'Hutan tropis',
                'conservation_status' => 'VU',
                'category' => 'langka',
                'is_featured' => false,
            ],
            [
                'name' => 'Katak Terbang',
                'local_name' => 'Katak Pohon',
                'scientific_name' => 'Rhacophorus reinwardtii',
                'description' => 'Katak dengan selaput kaki lebar untuk meluncur. Hidup di kanopi hutan hujan.',
                'image_path' => 'fauna/fa13.jpg',
                'habitat' => 'Kanopi hutan hujan',
                'conservation_status' => 'NT',
                'category' => 'umum',
                'is_featured' => false,
            ],
            [
                'name' => 'Biawak Air',
                'local_name' => 'Soa-soa',
                'scientific_name' => 'Varanus salvator',
                'description' => 'Reptil besar yang mahir berenang. Sering dijumpai di tepi Danau Lindu.',
                'image_path' => 'fauna/fa14.jpg',
                'habitat' => 'Tepi sungai dan danau',
                'conservation_status' => 'LC',
                'category' => 'umum',
                'is_featured' => false,
            ],
            [
                'name' => 'Ikan Sidat',
                'local_name' => 'Masapi',
                'scientific_name' => 'Anguilla marmorata',
                'description' => 'Ikan air tawar yang bermigrasi ke laut. Kuliner khas Danau Lindu.',
                'image_path' => 'fauna/fa15.jpg',
                'habitat' => 'Danau dan sungai',
                'conservation_status' => 'LC',
                'category' => 'umum',
                'is_featured' => false,
            ],
            [
                'name' => 'Belut Listrik',
                'local_name' => 'Sogili',
                'scientific_name' => 'Anguilla celebesensis',
                'description' => 'Ikan endemik Danau Lindu dengan kemampuan menghasilkan listrik lemah.',
                'image_path' => 'fauna/fa16.jpg',
                'habitat' => 'Danau Lindu',
                'conservation_status' => 'EN',
                'category' => 'endemik',
                'is_featured' => false,
            ],
            [
                'name' => 'Burung Julang',
                'local_name' => 'Kangkareng',
                'scientific_name' => 'Penelopides exarhatus',
                'description' => 'Burung enggang endemik dengan suara khas yang menggema di hutan.',
                'image_path' => 'fauna/fa17.jpg',
                'habitat' => 'Hutan pegunungan',
                'conservation_status' => 'VU',
                'category' => 'endemik',
                'is_featured' => false,
            ],
            [
                'name' => 'Musang Sulawesi',
                'local_name' => 'Musang Luwak',
                'scientific_name' => 'Macrogalidia musschenbroekii',
                'description' => 'Kucing liar terbesar di Sulawesi. Endemik dan sangat jarang terlihat.',
                'image_path' => 'fauna/fa18.jpg',
                'habitat' => 'Hutan primer pegunungan',
                'conservation_status' => 'VU',
                'category' => 'endemik',
                'is_featured' => false,
            ],
            [
                'name' => 'Tikus Raksasa',
                'local_name' => 'Tikus Bunomys',
                'scientific_name' => 'Bunomys chrysocomus',
                'description' => 'Tikus endemik berukuran besar. Indikator kesehatan ekosistem hutan.',
                'image_path' => 'fauna/fa19.jpg',
                'habitat' => 'Hutan pegunungan',
                'conservation_status' => 'LC',
                'category' => 'endemik',
                'is_featured' => false,
            ],
            [
                'name' => 'Kelelawar Buah',
                'local_name' => 'Paniki',
                'scientific_name' => 'Pteropus alecto',
                'description' => 'Kelelawar besar pemakan buah. Penting untuk penyerbukan dan penyebaran biji.',
                'image_path' => 'fauna/fa20.jpg',
                'habitat' => 'Hutan dan perkebunan',
                'conservation_status' => 'LC',
                'category' => 'umum',
                'is_featured' => false,
            ],
            [
                'name' => 'Kakatua Jambul Kuning',
                'local_name' => 'Kakatua',
                'scientific_name' => 'Cacatua sulphurea',
                'description' => 'Burung cerdas dengan jambul kuning. Terancam punah karena perdagangan ilegal.',
                'image_path' => 'fauna/fa21.jpg',
                'habitat' => 'Hutan dan tepi hutan',
                'conservation_status' => 'CR',
                'category' => 'langka',
                'is_featured' => true,
            ],
            [
                'name' => 'Rusa Sulawesi',
                'local_name' => 'Rusa',
                'scientific_name' => 'Rusa timorensis',
                'description' => 'Rusa yang beradaptasi dengan lingkungan Sulawesi. Sering terlihat di padang rumput.',
                'image_path' => 'fauna/fa22.jpg',
                'habitat' => 'Padang rumput dan hutan',
                'conservation_status' => 'VU',
                'category' => 'umum',
                'is_featured' => false,
            ],
            [
                'name' => 'Kuda Nil Kerdil',
                'local_name' => 'Anoa Gunung',
                'scientific_name' => 'Bubalus quarlesi',
                'description' => 'Anoa yang hidup di pegunungan. Lebih kecil dari anoa dataran rendah.',
                'image_path' => 'fauna/fa23.jpg',
                'habitat' => 'Hutan pegunungan',
                'conservation_status' => 'EN',
                'category' => 'endemik',
                'is_featured' => true,
            ],
            [
                'name' => 'Burung Cekakak',
                'local_name' => 'Raja Udang',
                'scientific_name' => 'Halcyon chloris',
                'description' => 'Burung pemburu ikan dengan warna biru cerah. Mudah dijumpai di tepi air.',
                'image_path' => 'fauna/fa24.jpg',
                'habitat' => 'Tepi sungai dan danau',
                'conservation_status' => 'LC',
                'category' => 'umum',
                'is_featured' => false,
            ],
        ];

        foreach ($faunaData as $index => $data) {
            $data['sort_order'] = $index;
            $data['is_active'] = true;
            Fauna::create($data);
        }
    }
}
